### PR TITLE
Updates to the oneAPI Community Forum pages

### PR DESCRIPTION
**Pull request by rodburns**
- Updated landing page with more information
- Added governance policy
- Added organization diagram
- Added table of upcoming events
- Added SIG descriptions

### CODE REVIEW

**Comment by rodburns** [comment]
You can see what the pages look like on my fork in case you did not realise. https://github.com/rodburns/oneAPI-tab

**Review by rscohn2 — COMMENTED** [review]
I can help resolve the failed checks.

**Comment by rscohn2** [comment]
Rod, please give rscohn2 write access to your fork so that I can fix the checks.

**Comment by rodburns** [comment]
> Rod, please give rscohn2 write access to your fork so that I can fix the checks.

I've invited you now.

**Review by sknepper — APPROVED** [review]
Looks good! I made a few minor comments. Thanks!

**Pull request merged**
